[WIP] Implement SetToggle and SetRepeat for Android
brim-borium/spotify_sdk pull request #54
Opened 2020-09-28 19:11 UTC by Joran-Dob

Implement SetToggle and SetRepeat for Android.

- Add SetToggle option for Android 
- Add SetRepeat option for Android

See issue #41

2020-10-02 10:45 UTC, fotiDim commented on example/lib/main.dart
> -                  onPressed: toggleShuffle,
We better leave the sample app as it is.

2020-10-05 11:52 UTC, Joran-Dob commented on example/lib/main.dart
> -                  onPressed: toggleShuffle,
@fotiDim Good point, accidentally left that testing line in the commit. Fixed it in the new commit and added a proper example.

2020-10-05 12:55 UTC, brim-borium requested changes

2020-10-05 12:55 UTC, brim-borium commented on example/.env
> +CLIENT_ID=cb584d96288349dcbc9af195fc91cb21
I think this can stay as it is because we are using a default client id here I think
@fotiDim correct me if I am wrong :)

2020-10-05 12:55 UTC, brim-borium commented on example/lib/main.dart
> +            DropdownButton<bool>(
Can we use some kind of switch instead of a dropdown button?

2020-10-05 13:00 UTC, Joran-Dob commented on example/.env
> +CLIENT_ID=cb584d96288349dcbc9af195fc91cb21
@brim-borium Thanks, will make the changes. 👍

2020-10-05 13:50 UTC, Joran-Dob commented on example/.env
> +CLIENT_ID=cb584d96288349dcbc9af195fc91cb21
@brim-borium actually when I'm running the app with the old client id used before I get the following error. 

`Authentication went wrong, INVALID_APP_ID`

Am I doing something wrong or is it maybe rate-limited or something similar?

2020-10-05 14:10 UTC, Joran-Dob commented on example/lib/main.dart
> +            DropdownButton<bool>(
@brim-borium changed it to a switch and added it to include the player state change for both repeat mode and shuffle mode.

2020-10-05 14:31 UTC, brim-borium commented on example/.env
> +CLIENT_ID=cb584d96288349dcbc9af195fc91cb21
Could be but the client id that you were using were probably one created via your own spotify developer account, so i don't think you want that in there. Probably best to leave the id as it is. In the readme of the package we describe the process how to add your own client id, so I think this should be fine

2020-10-05 15:36 UTC, Joran-Dob commented on example/.env
> +CLIENT_ID=cb584d96288349dcbc9af195fc91cb21
@brim-borium Clear, thanks! Readded the old token.

2020-10-05 17:12 UTC, brim-borium approved these changes

2020-10-05 17:12 UTC, brim-borium commented
Can be merged :)

2020-10-05 17:32 UTC, fotiDim approved these changes
Looks good on my end as well

2020-10-05 18:10 UTC, Joran-Dob commented
🎊

2020-10-05 18:10 UTC, merged