Adding asRadio and scope parameters
brim-borium/spotify_sdk pull request #70
Opened 2021-02-04 17:59 UTC by nishiths23

Adding asRadio and scope parameters which fixes #69

2021-02-05 17:43 UTC, fotiDim requested changes
Thanks for the PR. Some minor fixes and it should be good to go.

2021-02-05 17:43 UTC, fotiDim commented on lib/spotify_sdk.dart
> +      @required bool asRadio,
@nishiths23 `asRadio` should be optional I believe.

2021-02-05 17:43 UTC, fotiDim commented on lib/spotify_sdk.dart
> +      @required bool asRadio,
same as above

2021-02-05 17:43 UTC, fotiDim commented on ios/Classes/SwiftSpotifySdkPlugin.swift
> +                let asRadio = swiftArguments[SpotfySdkConstants.paramAsRadio] as? Bool else {
`asRadio` should not be part for the guard statement.

2021-02-05 17:43 UTC, fotiDim commented on ios/Classes/SwiftSpotifySdkPlugin.swift
> +                let asRadio = swiftArguments[SpotfySdkConstants.paramAsRadio] as? Bool else {
Same as above

2021-02-05 17:43 UTC, fotiDim commented on ios/Classes/SwiftSpotifySdkPlugin.swift
> +    private func connectToSpotify(clientId: String, redirectURL: String, accessToken: String? = nil, asRadio: Bool, additionalScopes: String? = nil) throws {
Let's give `asRadio` a default value of false.

2021-02-05 20:49 UTC, nishiths23 commented on lib/spotify_sdk.dart
> +      @required bool asRadio,
Updated

2021-02-05 20:49 UTC, nishiths23 commented on ios/Classes/SwiftSpotifySdkPlugin.swift
> +                let asRadio = swiftArguments[SpotfySdkConstants.paramAsRadio] as? Bool else {
Updated

2021-02-05 20:49 UTC, nishiths23 commented on ios/Classes/SwiftSpotifySdkPlugin.swift
> +    private func connectToSpotify(clientId: String, redirectURL: String, accessToken: String? = nil, asRadio: Bool, additionalScopes: String? = nil) throws {
Updated

2021-02-05 20:49 UTC, nishiths23 commented on lib/spotify_sdk.dart
> +      @required bool asRadio,
Updated

2021-02-05 21:58 UTC, fotiDim requested changes
One small improvement

2021-02-05 21:58 UTC, fotiDim commented on ios/Classes/SwiftSpotifySdkPlugin.swift
> +        }
```suggestion
```

can be deleted

2021-02-05 21:58 UTC, fotiDim commented on ios/Classes/SwiftSpotifySdkPlugin.swift
> +        if self.appRemote?.authorizeAndPlayURI("", asRadio: playAsRadio, additionalScopes: scopes) == false {
```suggestion
        if self.appRemote?.authorizeAndPlayURI("", asRadio: asRadio ?? false, additionalScopes: scopes) == false {
```

2021-02-06 05:46 UTC, nishiths23 commented on ios/Classes/SwiftSpotifySdkPlugin.swift
> +        if self.appRemote?.authorizeAndPlayURI("", asRadio: playAsRadio, additionalScopes: scopes) == false {
To be honest I was trying to avoid nil coalescing simply because it increases compile time exponentially😅

2021-02-06 07:10 UTC, fotiDim commented
@nishiths23 for the sake of conciseness we can do a small sacrifice :)

Can you merge master in your branch in order for the checks to succeed? Then I can merge it.

2021-02-06 10:27 UTC, fotiDim approved these changes

2021-02-06 10:28 UTC, merged