Feature/update packages
brim-borium/spotify_sdk pull request #74
Opened 2021-02-13 12:56 UTC by brim-borium

2021-02-13 13:32 UTC, fotiDim commented on example/android/app/src/main/kotlin/de/minimalme/spotify_sdk_example/MainActivity.kt
> -        GeneratedPluginRegistrant.registerWith(this)
Isn't this line needed?

2021-02-13 13:33 UTC, fotiDim commented on example/ios/Flutter/Debug.xcconfig
> +#include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
Seems kind of redundant

2021-02-13 13:33 UTC, fotiDim commented on example/ios/Flutter/Release.xcconfig
> +#include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
Same as above

2021-02-13 13:36 UTC, fotiDim commented on lib/spotify_sdk_web.dart
> +    playerContextEventChannel.setController(playerContextEventController);
Just curious, is it preferable to use a setter over properties?

2021-02-13 13:36 UTC, fotiDim commented on lib/spotify_sdk_web.dart
> +        MethodChannels.spotifySdk, const StandardMethodCodec(), registrar);
I haven't attempted to run it, but can we just remove `.messenger`?

2021-02-14 09:08 UTC, brim-borium commented on example/android/app/src/main/kotlin/de/minimalme/spotify_sdk_example/MainActivity.kt
> -        GeneratedPluginRegistrant.registerWith(this)
WIth the new Android Embedding v2 in flutter this is not needed anymore 
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

2021-02-14 09:09 UTC, brim-borium commented on example/ios/Flutter/Debug.xcconfig
> +#include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
Huh don't know what happened there ^^

2021-02-14 09:09 UTC, brim-borium commented on example/ios/Flutter/Release.xcconfig
> +#include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
Huh don't know what happened there ^^ Will remove these changes

2021-02-14 09:10 UTC, brim-borium commented on lib/spotify_sdk_web.dart
> +    playerContextEventChannel.setController(playerContextEventController);
Yes, setting the controller over a property has been deprecated and the setController is the way to go

2021-02-14 09:10 UTC, brim-borium commented on lib/spotify_sdk_web.dart
> +        MethodChannels.spotifySdk, const StandardMethodCodec(), registrar);
Yes, messenger has also been deprecated because this was just giving back the registrar somehow 🤷 . Now just the registrar is needed

2021-02-14 17:40 UTC, brim-borium commented on example/ios/Flutter/Release.xcconfig
> +#include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
I just tried to build on iOS (only simulator, got no iPhone at the moment) and these files were added automatically. Do you know if the whole file can possibly be ignored ?

2021-02-14 17:47 UTC, brim-borium commented
@fotiDim Could you do a test run on iOS ? Just to make sure I did not break anything ^^

2021-02-14 22:12 UTC, fotiDim requested changes

2021-02-14 22:12 UTC, fotiDim commented on example/pubspec.yaml
> +  sdk: ">=2.11.0 <3.0.0"
That is actually too high. Latest stable Dart  is `2.10.5` and I am getting:
```
The current Dart SDK version is 2.10.5.                                 

Because spotify_sdk_example requires SDK version >=2.11.0 <3.0.0, version solving failed.
```

2021-02-14 22:12 UTC, fotiDim commented on .github/workflows/spotify_sdk.yml
> +          channel: 'beta'
Was there a reason why we switched to beta?

2021-02-15 07:11 UTC, brim-borium commented on example/pubspec.yaml
> +  sdk: ">=2.11.0 <3.0.0"
Yeah I did this because on pub.dev the scoring system said we shoulduse preview versions of some packages, because they were declared as the up-to-date version. Not sure if we should keep it like this or reroll some of the packages updates
![image](https://user-images.githubusercontent.com/4504079/107915688-40888180-6f65-11eb-86d2-fdf1de3cc621.png)

2021-02-15 07:11 UTC, brim-borium commented on example/pubspec.yaml
> +  sdk: ">=2.11.0 <3.0.0"
json_annotation is one of these for example

2021-02-15 07:12 UTC, brim-borium commented on .github/workflows/spotify_sdk.yml
> +          channel: 'beta'
Needed to switch to beta because of the updated packages

2021-02-15 07:40 UTC, fotiDim commented on .github/workflows/spotify_sdk.yml
> -on: [push, pull_request]
Why not `pull_request`?

2021-02-15 07:42 UTC, brim-borium commented on .github/workflows/spotify_sdk.yml
> -on: [push, pull_request]
Because this will duplicate our runtime or did I miss something?

2021-02-15 07:45 UTC, brim-borium commented
![image](https://user-images.githubusercontent.com/4504079/107918337-c1e21300-6f69-11eb-9198-f2740529486b.png)

One thing I just discovered. It seems that on pub.dev they are using currently the beta version of flutter sdk. (For transitioning to null safety I think) We are getting the info on static analysis that something was deprecated after v1.24.-07.0.pre So we could go with that and also upgrade to beta, including our packages we are using, or we do a preview version after releasing this version, where we will upgrade everything

2021-02-15 07:54 UTC, fotiDim commented on .github/workflows/spotify_sdk.yml
> -on: [push, pull_request]
Not sure if it would run twice when opening a new PR. According to the documentation for `push`:
```
Runs your workflow when someone pushes to a repository branch, which triggers the push event.
```
I interpret that that it would also run on branches that don't have open PRs.


From what I read [here](https://github.community/t/trigger-workflow-for-a-pull-request-and-for-all-subsequent-commits-in-it/17996/2) `pull_request` will also trigger for additional commits.

I think just this is enough:
```
on: pull_request
```

2021-02-15 07:59 UTC, fotiDim commented
> ![image](https://user-images.githubusercontent.com/4504079/107918337-c1e21300-6f69-11eb-9198-f2740529486b.png)
> 
> @fotiDim One thing I just discovered. It seems that on pub.dev they are using currently the beta version of flutter sdk. (For transitioning to null safety I think) We are getting the info on static analysis that something was deprecated after v1.24.-07.0.pre So we could go with that and also upgrade to beta, including our packages we are using, or we do a preview version after releasing this version, where we will upgrade everything.
> 
> Will probably go with the last idea, to have 2 seperate versions of the package.
> 
> https://dart.dev/tools/pub/publishing#publishing-previews

Oh I see. Is there any way to be on the beta channel and have our flutter and sdk version requirements low enough for `stable` users?

2021-02-15 08:02 UTC, fotiDim commented on example/ios/Flutter/Release.xcconfig
> +#include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
Then let them be. I will also try to build when we sort out the stable/beta issue.

2021-02-15 08:28 UTC, fotiDim commented
Null safety will enter stable [soon](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730) so perhaps it is worth sticking to the stable channel for now and live with the linting errors.

2021-02-15 08:31 UTC, brim-borium commented
> > ![image](https://user-images.githubusercontent.com/4504079/107918337-c1e21300-6f69-11eb-9198-f2740529486b.png)
> > @fotiDim One thing I just discovered. It seems that on pub.dev they are using currently the beta version of flutter sdk. (For transitioning to null safety I think) We are getting the info on static analysis that something was deprecated after v1.24.-07.0.pre So we could go with that and also upgrade to beta, including our packages we are using, or we do a preview version after releasing this version, where we will upgrade everything.
> > Will probably go with the last idea, to have 2 seperate versions of the package.
> > https://dart.dev/tools/pub/publishing#publishing-previews
> 
> Oh I see. Is there any way to be on the beta channel and have our Flutter and Dart sdk minimum version requirements low enough for `stable` users?

Yeah I think we can use as is right now, I reverted the changes made before. If I get the link that I posted correctly, we can publish a version with something like this pub.dev will automatically tag this as preview

> environment:
>   sdk: '>=2.12.0-259.8.beta <3.0.0'

2021-02-15 08:36 UTC, brim-borium commented on .github/workflows/spotify_sdk.yml
> -on: [push, pull_request]
I'll try that :)

2021-02-15 08:38 UTC, brim-borium commented on .github/workflows/spotify_sdk.yml
> -on: [push, pull_request]
Looks good :)

2021-02-15 08:53 UTC, fotiDim approved these changes
LGTM

2021-02-15 08:58 UTC, merged