Add null safety to example app
brim-borium/spotify_sdk pull request #93
Opened 2021-04-08 15:19 UTC by fotiDim

What the title says 👆
Please test it before approving!

2021-04-08 19:18 UTC, brim-borium reviewed
The files look good but during testing I found an issue in the spotify_sdk.dart

`var capabilitiesJson= await (_channel.invokeMethod<String>(MethodNames.getCapabilities) as FutureOr<String>);`

The cast with `as FutureOr<String>` seems not to work with `_channel.invokeMethod<String>()`. This returns a `Future<String?>`

We can go two ways here, returning null or throw an exception. Not sure what's better here

```
static Future<Capabilities?> getCapabilities(
      {required String spotifyUri}) async {
    try {
      var capabilitiesJson =
          await _channel.invokeMethod<String>(MethodNames.getCapabilities);

      if (capabilitiesJson!.isNotEmpty) {
        var capabilitiesMap =
            jsonDecode(capabilitiesJson) as Map<String, dynamic>;
        return Capabilities.fromJson(capabilitiesMap);
      }

      return null;
    } on Exception catch (e) {
      _logException(MethodNames.getCapabilities, e);
      rethrow;
    }
  }

```

Same goes for all the places we use `as FutureOr<String>`

2021-04-09 10:19 UTC, fotiDim commented
@brim-borium I hope I address what you pointed out.
It turned out 2.0 was not working for iOS. I had to fix some bugs in the null safety migration. Let's try to make a release soonish. I have one more PR coming up after this is merged.

2021-04-09 10:21 UTC, brim-borium commented
Can this be merged then and you fix the iOS issues in a separate pr or do you want to do this here?

2021-04-09 10:27 UTC, fotiDim commented on lib/models/connection_status.dart
> +  final String? message;
This is for iOS. On successful connection we are only sending back the `connected` bool without any message.

2021-04-09 10:27 UTC, fotiDim commented on lib/models/connection_status.g.dart
> +    json['message'] as String?,
I had to edit this. Not sure how it is regenerated

2021-04-09 10:29 UTC, fotiDim commented on example/lib/main.dart
> +  Future<void> setShuffle(bool shuffle) async {
This is a breaking change. I documented this in the changelog.

2021-04-09 10:30 UTC, fotiDim commented on example/lib/main.dart
> -                        onChanged: setRepeatMode,
How was that even working

2021-04-09 10:30 UTC, fotiDim commented on example/lib/main.dart
> -      ),
I hope you don't mind removing that.

2021-04-09 10:33 UTC, fotiDim commented
> Can this be merged then and you fix the iOS issues in a separate pr or do you want to do this here?

The iOS issues are fixed in this PR. The upcoming one is just for a new "feature".

2021-04-09 14:37 UTC, brim-borium requested changes

2021-04-09 14:37 UTC, brim-borium commented on CHANGELOG.md
> +## 2.0.1
If you add a breaking change we must raise the version to 3.0.0

2021-04-09 14:37 UTC, brim-borium commented on example/lib/main.dart
> -      ),
Fine with that :)

2021-04-09 14:37 UTC, brim-borium commented on example/lib/main.dart
> -                        onChanged: setRepeatMode,
What do you mean?

2021-04-09 15:06 UTC, fotiDim commented on example/lib/main.dart
> -                        onChanged: setRepeatMode,
We were passing the function as a lambda but `setRepeatMode` requires an argument. How was it getting that? I tested it and did not work for me.

2021-04-09 15:08 UTC, fotiDim commented on CHANGELOG.md
> +## 2.0.1
It's a bummer that we spotted it now after bumping to 2.0. It is a very minor change which I don't think justifies a new major release just for that. My suggestion is that we either set it to 2.1.0 or we skip it for now and do this change later.

2021-04-10 07:43 UTC, brim-borium commented on CHANGELOG.md
> +## 2.0.1
Then lets bump this to 2.1.0

2021-04-10 07:45 UTC, brim-borium requested changes
Lets set the version to 2.1.0 in the changelog and this should be fine

2021-04-10 07:45 UTC, brim-borium commented on example/lib/main.dart
> -                        onChanged: setRepeatMode,
Actually I am not sure how that happened 🤷

2021-04-10 08:20 UTC, fotiDim commented on CHANGELOG.md
> +## 2.0.1
@brim-borium done

2021-04-10 08:32 UTC, brim-borium approved these changes

2021-04-10 08:33 UTC, merged